name: BukkitCommons
main: org.bukkit.commons.internal.plugin.BukkitCommonsPlugin
version: 1.0.0
load: STARTUP
website: https://dev.bukkit.org/
description: Next-generation plugin development framework for Bukkit API.
